### ISSUE TITLE
Set alphabetized ordering for arguments [feature]

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#26]
There is no cononical ordering for kamodo's automated signatures. This makes it difficult to test default signature registration.

Here's a test the illustrates the issue:

```python
from sympy import Symbol, sympify
from kamodo import Kamodo

from kamodo.util import get_args

def test_alphabetize():
    k = Kamodo(f='x + y + a + b + c')

    args = get_args(k.f)

    answer = tuple('a b c x y'.split())
    try:
        assert args == answer
    except:
        print("{} != {}".format(args, answer))
        raise
        
test_alphabetize()
```
On my machine, I get
```console
('c', 'b', 'x', 'a', 'y') != ('a', 'b', 'c', 'x', 'y')
```

To fix:

1. Add the following code to kamodo.py

```python
def alphabetize(symbols):
    """alphabetical ordering for the input symbols"""
    # can't use > on symbols, so need to convert to str first
    return tuple(Symbol(symbol_) for symbol_ in sorted([str(_) for _ in symbols]))
```

2. and in Kamodo.__setitem__:
```python
...

            if not isinstance(symbol, Symbol):
                if isinstance(lhs_expr, Symbol):
                    symbol = Function(lhs_expr)(*tuple(alphabetize(rhs_expr.free_symbols))) # alphabetize here
                else:  # lhs is already a function
                    symbol = lhs_expr
                lhs_str = str(symbol)
                sym_name = sym_name.replace(str(lhs_expr), lhs_str)
```

3. Add the above test to `test_kamodo.py`

All the tests should pass (including the new one) with the above changes.

**Comment by pythonguru101** [comment]
The main failed cases were resolved except the below one: Can you ask someone to explain why it should register as h(a,y,x)?-->line no 609?
basically why k['h'] = 'a + y + f' this should have registered as h(a,y,x) not h(a,x,y)?
![2022-01-25](https://user-images.githubusercontent.com/26586879/151109569-a8952939-70a0-47c3-b243-ced0912dd432.png)

**Comment by pythonguru101** [comment]
As per issue-26, the input symbols must be in alphabetical order, so I was told to add a function 'alphabetize' and call that function at the symbol formation like this:

symbol = Function(lhs_expr)(*tuple(alphabetize(rhs_expr.free_symbols)))

Now according to this test case below should register as h(a,y,x)
k['h'] = 'a + y + f' # should have registered h(a,y,x)
# get_args will return a string list, which should match arguments of h
for a, b in zip(k.signatures['h']['symbol'].args, get_args(k.h)):
assert str(a) == b

This will never happen if I have to call alphabetize function as this will change the alphabetical order and that's why the test is failing with assertion error.

So can you please tell me about this and based on what for this particular cases the registration should be h(a,y,x).

The rest of the failed test cases have been taken care of

**Comment by asher-pembroke** [comment]
The default order of arguments should be alphabetical *both* in *args *and* in **kwargs but kwargs still need to go last, like this:

```python
k['f'] = kamodofy(lambda x, g=3, a=2: a*x**g) # it's ok for g to come before a here
k['g'] = 'b + c + y + f' # should register as g(b,c,x,y,a,g)
```
So both (`b`, `c`, `x`, `y`) are arranged alphabetically and (`a`, `g`) are key-word arguments and are also arranged alphabetically but they still come **after** the positional arguments.
